In [1]:
import numpy as np
import pandas as pd

In [2]:
ar1=np.array([1,2,'a','hello',[1,2,3],{'one':100,'two':200}])
ar2=np.array([list(range(6)),
              list('abcdef'),
              [True, False, True, False, True, True]])
print(ar1,'\na1的shape为：',ar1.shape, '\n-------')
print(ar2,'\na2的shape为：',ar2.shape, '\n-------')

[1 2 'a' 'hello' list([1, 2, 3]) {'one': 100, 'two': 200}] 
a1的shape为： (6,) 
-------
[['0' '1' '2' '3' '4' '5']
 ['a' 'b' 'c' 'd' 'e' 'f']
 ['True' 'False' 'True' 'False' 'True' 'True']] 
a2的shape为： (3, 6) 
-------


In [5]:
ar1 = np.linspace(5,15,10,endpoint=False)
ar2 = np.arange(5,15)
print (ar1,ar2)

[  5.   6.   7.   8.   9.  10.  11.  12.  13.  14.] [ 5  6  7  8  9 10 11 12 13 14]


In [8]:
ar1=np.zeros((4,4))
ar2=np.ones((2,3))
ar3=np.eye(3,dtype=int)
print (ar1,ar2,ar3)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]] [[ 1.  1.  1.]
 [ 1.  1.  1.]] [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [9]:
ar=np.arange(20)
print (ar.reshape(4,5))
print (np.resize(ar,(5,6)))   #ar.resize本身修改，不返回

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19  0  1  2  3]
 [ 4  5  6  7  8  9]]


In [10]:
ar=np.arange(16).reshape(4,4)
print (ar.astype(str))

[['0' '1' '2' '3']
 ['4' '5' '6' '7']
 ['8' '9' '10' '11']
 ['12' '13' '14' '15']]


In [12]:
ar=np.arange(16).reshape(4,4)

result = ar*10+100
print (result)
print (result.mean())
print (result.sum())

[[100 110 120 130]
 [140 150 160 170]
 [180 190 200 210]
 [220 230 240 250]]
175.0
2800


In [13]:
ar=np.arange(25).reshape(5,5)
print (ar[4])
print(ar[:2,3:])
print (ar[3][2])

[20 21 22 23 24]
[[3 4]
 [8 9]]
17


In [15]:
ar = np.arange(10).reshape(2,5)
print(ar, '\n-------')
print('大于5的值为：',ar[ar>5])
print('大于5的值为：',ar[[ar>5]])

[[0 1 2 3 4]
 [5 6 7 8 9]] 
-------
大于5的值为： [6 7 8 9]
大于5的值为： [6 7 8 9]


In [18]:
ar=np.arange(25,dtype=np.float32).reshape(5,5)
print (ar)
ar[:2,:2]=np.random.rand(2,2)
print (ar)

[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.]]
[[  0.27110162   0.19690138   2.           3.           4.        ]
 [  0.23234746   0.43459901   7.           8.           9.        ]
 [ 10.          11.          12.          13.          14.        ]
 [ 15.          16.          17.          18.          19.        ]
 [ 20.          21.          22.          23.          24.        ]]


In [22]:
ar=np.random.normal(size=(2,5))
print (ar)
ar2=np.random.randn(2,5)
print(ar2)

[[-0.27825526  1.0232843  -0.75142383 -1.2532579   0.41065341]
 [-0.83238026 -0.11646198 -1.5150271   0.81121877  0.10350436]]
[[ 0.23429174  1.7376537  -0.28805175  0.24122553  0.82603751]
 [-0.37253138  0.26773254  0.45113759  0.27451942  1.23642871]]


In [28]:
ar=np.random.randint(0,100,size=(10,10))
import os
os.chdir('C:/Users/hp/Desktop/')
np.savetxt('a.txt',ar,delimiter=',',fmt='%i')